### ISSUE TITLE
Error deleting router interface (unlink tenant bridge from tenant router)

### ISSUE THREAD

**Issue by AbelNavarro** [midokura/midonet-openstack#23]
To bind a tenant router with the tenant bridge (network) we do:

```
quantum router-interface-add <tenant router> <tenant bridge subnet id>
```

when trying to unbind the two an error occurs:

```
quantum router-interface-delete <tenant router> <tenant bridge subnet id>
```

```
2013-02-25 17:07:42    ERROR [quantum.api.v2.resource] remove_router_interface failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/quantum/api/v2/resource.py", line 96, in resource
    result = method(request=request, **args)
  File "/usr/lib/python2.7/dist-packages/quantum/api/v2/base.py", line 158, in _handle_action
    return getattr(self._plugin, name)(request.context, id, body)
  File "/usr/lib/pymodules/python2.7/midolman/quantum/plugin.py", line 899, in remove_router_interface
    assert found
AssertionError
```

**Comment by adjohn** [comment]
Was there a floating IP associated while trying to remove the interface?  If so, there is a known bug in quantum on this: https://bugs.launchpad.net/quantum/+bug/1080638

**Comment by AbelNavarro** [comment]
I'd say I wasn't but I'll need to try again.
