### ISSUE TITLE
Get ports from bridge fails

### ISSUE THREAD

**Issue by AbelNavarro** [midokura/midonet-openstack#25]
I'm using MidoNet python client. I'm trying to get all the ports for a bridge. I can successfully get all the ports for one of the bridges. But in other bridge I get this from python:

```
DEBUG:nova...midonet.client:====================
DEBUG:nova...midonet.client:Req: (GET on http://10.0.1.2:8080/midolmanj-mgmt/bridges/63ecdbd3-a67d-4b23-9d20-685933d6ee77/ports)
DEBUG:nova...midonet.client:Req headers: {'Content-Type': 'application/vnd.com.midokura.midolman.mgmt.collection.Port+json', 'X-Auth-Token': u'b3b88fef8451434da802eb5957d4d4ed'}
DEBUG:nova...midonet.client:Req Body: {}
DEBUG:nova...midonet.client:Resp: {'status': '500', 'access-control-expose-headers': 'Location', 'transfer-encoding': 'chunked', 'server': 'Apache-Coyote/1.1', 'connection': 'close', 'date': 'Mon, 04 Mar 2013 10:02:23 GMT', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET, POST, PUT, DELETE, OPTIONS', 'content-type': 'application/vnd.com.midokura.midolman.mgmt.Error+json'}
DEBUG:nova...midonet.client:Resp Body: {"message":"Unrecoverable server error has occurred.","code":500}
DEBUG:nova...midonet.client:====================
ERROR:nova...midonet.client:(GET on http://10.0.1.2:8080/midolmanj-mgmt/bridges/63ecdbd3-a67d-4b23-9d20-685933d6ee77/ports)  got an error status 500
ERROR:nova...midonet.client:Raising an exeption: (<HTTPInternalServerError at 0x2daa6e0 500 Internal Server Error>): '{"message":"Unrecoverable server error has occurred.","code":500}'
Traceback (most recent call last):
  File "quantum-midonet.py", line 168, in <module>
    bridge_ports = bridge.get_ports()
  File "/usr/lib/pymodules/python2.7/midonet/client/bridge.py", line 53, in get_ports
    return self.get_children(self.dto['ports'], query, headers, BridgePort)
  File "/usr/lib/pymodules/python2.7/midonet/client/resource_base.py", line 33, in get_children
    res, dtos =  self.web_resource.get(uri, query=query, headers=headers)
  File "/usr/lib/pymodules/python2.7/midonet/client/web_resource.py", line 72, in get
    return self._do_request(uri, 'GET', headers=headers)
  File "/usr/lib/pymodules/python2.7/midonet/client/web_resource.py", line 61, in _do_request
    raise e
webob.exc.HTTPInternalServerError: {"message":"Unrecoverable server error has occurred.","code":500}
```

It seems it's related to a specific port not wanting to be listed. This is the output from midolmanj-mgmt.log (tomcat7):

```
11:02:24.304 DEBUG [] ClientCnxn - Reading reply sessionid:0x13cc92fa18e0004, packet:: clientPath:null serverPath:null finished:false header:: 1469983,8  replyHeader:: 1469983,17179931655,0  request:: '/midonet/v1/bridges/63ecdbd3-a67d-4b23-9d20-685933d6ee77/logical-ports,F  response:: v{'55050e30-c924-4172-97bc-6d0d5cfc6f42}
11:02:24.305 DEBUG [] ClientCnxn - Reading reply sessionid:0x13cc92fa18e0004, packet:: clientPath:null serverPath:null finished:false header:: 1469984,3  replyHeader:: 1469984,17179931655,-101  request:: '/midonet/v1/ports/55050e30-c924-4172-97bc-6d0d5cfc6f42,F  response::
11:02:24.307 ERROR [] ExceptionFilter - Resource method error:
java.lang.UnsupportedOperationException: Cannot instantiate this port type.
    at com.midokura.midonet.api.network.PortFactory.createPort(PortFactory.java:34) ~[PortFactory.class:na]
    at com.midokura.midonet.api.network.rest_api.PortResource$BridgePortResource.list(PortResource.java:331) ~[PortResource$BridgePortResource.class:na]
    at sun.reflect.GeneratedMethodAccessor565.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_09]
    at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_09]
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:134) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:134) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469) [jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400) [jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349) [jersey-server-1.10.jar:1.10]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339) [jersey-server-1.10.jar:1.10]
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) [jersey-servlet-1.10.jar:1.10]
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537) [jersey-servlet-1.10.jar:1.10]
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708) [jersey-servlet-1.10.jar:1.10]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722) [tomcat-servlet-api-3.0.jar:na]
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [guice-servlet-3.0.jar:na]
    at com.midokura.midonet.api.auth.AuthFilter.doFilter(AuthFilter.java:127) [AuthFilter.class:na]
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
    at com.midokura.midonet.api.auth.cors.CrossOriginResourceSharingFilter.doFilter(CrossOriginResourceSharingFilter.java:113) [CrossOriginResourceSharingFilter.class:na]
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [guice-servlet-3.0.jar:na]
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224) [tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169) [tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) [tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) [tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927) [tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [tomcat-catalina-7.0.26.jar:7.0.26]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987) [tomcat-coyote-7.0.26.jar:7.0.26]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579) [tomcat-coyote-7.0.26.jar:7.0.26]
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309) [tomcat-coyote-7.0.26.jar:7.0.26]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_09]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_09]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_09]
```

**Comment by AbelNavarro** [comment]
The bridge I'm trying to get the ports from is the OpenstackMetadataBridge.

```
+-------------------------+--------------------------------------+
|   Bridge/Network Name   |                  ID                  |
+-------------------------+--------------------------------------+
| OpenstackMetadataBridge | 63ecdbd3-a67d-4b23-9d20-685933d6ee77 |
+-------------------------+--------------------------------------+
```

**Comment by tomoe** [comment]
closing as obsolete.
