### ISSUE TITLE
VM fails to launch because of SG handler missed the opportunity to handle "default"

### ISSUE THREAD

**Issue by tomoe** [midokura/midonet-openstack#32]
log inside nova-compute.

<pre>

2013-05-16 14:39:47.800 DEBUG nova...midonet.nova.network.midonet_lib [req-b4447b37-e5e4-4ac2-9820-8f72bb11b
a42 2ab52b9959404781bb8d611c9fc3643c a541ae256e984cb48c685c38279d7fae] name=u'default' create_for_vif /usr/lib/pymodules/python2.7/midonet/nova/network/midonet_lib.py:370
2013-05-16 14:39:47.801 DEBUG nova...midonet.nova.network.midonet_lib [req-b4447b37-e5e4-4ac2-9820-8f72bb11ba42 2ab52b9959404781bb8d611c9fc3643c a541ae256e984cb48c685c38279d7fae] rules=[] create_for_vif /usr/lib/pymodules/python2.7/midonet/nova/network/midonet_lib.py:371
2013-05-16 14:39:47.829 ERROR nova.compute.manager [req-b4447b37-e5e4-4ac2-9820-8f72bb11ba42 2ab52b9959404781bb8d611c9fc3643c a541ae256e984cb48c685c38279d7fae] [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299] Instance failed to spawn
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299] Traceback (most recent call last):
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299]   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1089, in _spawn
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299]     block_device_info)
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 1520, in spawn
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299]     block_device_info)
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299]   File "/usr/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 2434, in _create_domain_and_network
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299]     self.firewall_driver.prepare_instance_filter(instance, network_info)
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299]   File "/usr/lib/pymodules/python2.7/midonet/nova/network/sg.py", line 72, in prepare_instance_filter
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299]     vif_chains, CONF.allow_same_net_traffic)
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299]   File "/usr/lib/pymodules/python2.7/midonet/nova/network/midonet_lib.py", line 380, in create_for_vif
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299]     assert jump_chain_id != None
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299] AssertionError
2013-05-16 14:39:47.829 3944 TRACE nova.compute.manager [instance: 6192634f-5cea-4e21-b3a4-fc362bbcd299] 
</pre>

**Comment by tomoe** [comment]
This is because sg handler had not been configured correctly when the "default" sg was created. 

Will add a workaround to ensure SG resources are created properly; when it's not there, it'll be created. 

Note that this is a fundamental problem of event driven plugin approach in general including Quantum plugin. For example, if one wants to migrate from OVS plugin to ours, right now we need to do offline conversion for existing resources.
We may need to do periodical-ensuring-with-polling along side with event handling.
